---
- name: ansible-role-generic-template | Verify connection
  ansible.builtin.ping:
  register: ping_result
  

- name: ansible-role-generic-template | debug
  debug:
    msg: "{{ ping_result }}"


- name: ansible-role-podmanservice-traefik| install prereq for redhat
  include_tasks:  redhat.yml
  when: ansible_os_family == "RedHat"

- name: ansible-role-generic-template  | install prereq for ubuntu
  include_tasks:  ubuntu.yml
  when: ansible_os_family == "Debian"

