- name: "ansible-role-podmanservice-traefik| Verify redhat version"
  assert:
    fail_msg: "{{ role_name }} only supports ubuntu  20 and newer!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} version {{ ansible_distribution_version }}"
    quiet: "{{ not ansible_check_mode }}"
    that:
      ansible_distribution|lower == "ubuntu" and ansible_distribution_major_version|int in [22,23,24,25,26,27,28,29,30,31,32,33,34,35] 
  vars:
    role_name: "ansible-role-podmanservice-traefik"

