- name: "ansible-role-generic-template| Verify ubuntu version"
  command: "echo 'Hello World!'"
  register: command_result
  changed_when: false
  failed_when: false
  check_mode: false
  ignore_errors: true
  when: ansible_os_family == "Debian"

- name: "ansible-role-generic-template| debug"
  debug:
    msg: "{{ command_result }}"
  when: ansible_os_family == "Debian"
  
  
  

